HDBASE=&FC40
PATCH_IDE=TRUE
PATCH_SD=FALSE
PATCH_FULL_ACCESS=TRUE
PATCH_INFO=TRUE
PATCH_UNSUPPORTED_OSFILE=TRUE
PATCH_PRESERVE_CONTEXT=TRUE
TEST_SHIFT=TRUE
INCLUDE_FLOPPY=TRUE
PATCH_IDFS=FALSE

include "adfs150.asm"
