HDBASE=&FE80
PATCH_IDE=FALSE
PATCH_SD=FALSE
PATCH_FULL_ACCESS=FALSE
PATCH_INFO=FALSE
PATCH_UNSUPPORTED_OSFILE=FALSE
PATCH_PRESERVE_CONTEXT=FALSE
TEST_SHIFT=FALSE
INCLUDE_FLOPPY=FALSE
PATCH_IDFS=TRUE

include "adfs150.asm"
